sudo: required
services: 
        - docker

before_install:
        - docker build -t tman5/docker-react -f Dockerfile.dev .

script:
        - docker run tman5/docker-react npm run test -- --coverage
